# Single source of truth for all brand cards and brand pages.
# tier: "OE Manufacturer" | "Premium Aftermarket" | "Value Line"
# systems keys -> see SYSTEMS

SYSTEMS = {
    "braking": "Braking",
    "filtration": "Filtration",
    "suspension": "Suspension & Steering",
    "transmission": "Transmission & Clutch",
    "engine": "Engine & Timing",
    "cooling": "Cooling & Climate",
    "electrical": "Electrical & Ignition",
    "fuel": "Fuel & Injection",
    "commercial": "Commercial Vehicles",
}

BILSTEIN = "https://partsfinder.bilsteingroup.com/en"
ZF = "https://aftermarket.zf.com/en/aftermarket-portal/our-catalog/search-by-vehicle/"
SCHAEFFLER = "https://www.schaeffler.com/en/divisions-products/automotive-aftermarket/"
CONTI = "https://www.continental-aftermarket.com/en-en/catalogs/online-catalogs"

BRANDS = [
    dict(slug="ate", name="ATE", group="AUMOVIO (formerly Continental)", hq="Germany", tier="OE Manufacturer",
         systems=["braking"], catalog=CONTI,
         desc="Brake system specialist: brake pads, discs, calipers, hydraulics and brake fluid to original-equipment standards."),
    dict(slug="beru", name="BERU", group="BorgWarner", hq="USA", tier="OE Manufacturer",
         systems=["electrical", "engine"], catalog="https://www.borgwarner.com/aftermarket/ignition-technologies",
         desc="Glow plugs, spark plugs, ignition coils and ignition leads for petrol and diesel engines."),
    dict(slug="blue-print", name="Blue Print", group="bilstein group", hq="Germany", tier="Premium Aftermarket",
         systems=["braking", "filtration", "suspension", "engine", "cooling"], catalog=BILSTEIN,
         desc="Specialist range for Asian and American vehicles, covering service, braking, chassis and engine parts."),
    dict(slug="boge", name="BOGE", group="ZF Group", hq="Germany", tier="OE Manufacturer",
         systems=["suspension"], catalog=ZF,
         desc="Shock absorbers, suspension struts and anti-vibration components for passenger cars."),
    dict(slug="borgwarner", name="BorgWarner", group="BorgWarner", hq="USA", tier="OE Manufacturer",
         systems=["engine", "transmission"], catalog="https://www.borgwarner.com/aftermarket",
         desc="Turbochargers, timing systems and drivetrain technologies for passenger and commercial vehicles."),
    dict(slug="bosch", name="Bosch", group="Robert Bosch", hq="Germany", tier="OE Manufacturer",
         systems=["braking", "filtration", "electrical", "fuel", "engine"],
         catalog="https://www.boschaftermarket.com/gb/en/parts/product-search.html",
         desc="Broad automotive range: brakes, filters, wipers, starters and alternators, sensors, fuel injection and ignition."),
    dict(slug="brembo", name="Brembo", group="Brembo", hq="Italy", tier="OE Manufacturer",
         systems=["braking"], catalog="https://www.bremboparts.com/",
         desc="High-performance brake discs, pads, calipers and drums trusted by leading European car makers."),
    dict(slug="dayco", name="Dayco", group="Dayco", hq="USA", tier="OE Manufacturer",
         systems=["engine", "cooling"], catalog="https://www.dayco.com/emea-en/catalog/",
         desc="Timing belts and kits, auxiliary drive belts, tensioners, pulleys and water pumps."),
    dict(slug="delphi", name="Delphi", logo="phinia", group="PHINIA (Delphi Technologies)", hq="USA", tier="OE Manufacturer",
         systems=["fuel", "braking", "suspension", "electrical"], catalog="https://www.delphiautoparts.com/",
         desc="Diesel and gasoline fuel injection, braking, steering and suspension, and engine-management components."),
    dict(slug="fag", name="FAG", group="Schaeffler", hq="Germany", tier="OE Manufacturer",
         systems=["suspension"], catalog=SCHAEFFLER,
         desc="Wheel bearings, wheel-bearing kits and chassis components engineered to OE specification."),
    dict(slug="febi", name="febi", group="bilstein group", hq="Germany", tier="Premium Aftermarket",
         systems=["braking", "filtration", "suspension", "engine", "cooling", "electrical", "commercial"], catalog=BILSTEIN,
         desc="One of the widest ranges for European cars and trucks, from chassis and engine parts to service items."),
    dict(slug="filtron", name="FILTRON", group="MANN+HUMMEL", hq="Germany", tier="Premium Aftermarket",
         systems=["filtration"], catalog="https://filtron.eu/en/catalog.html",
         desc="Oil, air, fuel and cabin filters with wide coverage for European and Asian vehicles."),
    dict(slug="hepu", name="HEPU", group="HEPU Autoteile", hq="Germany", tier="Premium Aftermarket",
         systems=["cooling", "engine"], catalog="https://www.hepu.de/en/parts-catalogue/",
         desc="Water pumps, water pump and timing-belt kits, thermostats and cooling-system components."),
    dict(slug="ina", name="INA", group="Schaeffler", hq="Germany", tier="OE Manufacturer",
         systems=["engine"], catalog=SCHAEFFLER,
         desc="Timing belt and chain kits, tensioners, idlers and belt-drive components for engines."),
    dict(slug="knecht", name="KNECHT", group="MAHLE", hq="Germany", tier="Premium Aftermarket",
         systems=["filtration"], catalog="https://www.mahle.com/en/products-and-services/aftermarket/",
         desc="MAHLE's filter brand: oil, air, fuel and cabin filters with wide coverage for European vehicles."),
    dict(slug="lemforder", name="LEMFÖRDER", group="ZF Group", hq="Germany", tier="OE Manufacturer",
         systems=["suspension"], catalog=ZF,
         desc="Steering and suspension: control arms, ball joints, tie rods, stabilizer links and rubber-metal parts."),
    dict(slug="luk", name="LuK", group="Schaeffler", hq="Germany", tier="OE Manufacturer",
         systems=["transmission"], catalog=SCHAEFFLER,
         desc="Clutch kits, dual-mass flywheels and clutch release systems for manual and dual-clutch transmissions."),
    dict(slug="mahle", name="MAHLE", group="MAHLE", hq="Germany", tier="OE Manufacturer",
         systems=["filtration", "engine", "cooling"], catalog="https://www.mahle.com/en/products-and-services/aftermarket/",
         desc="Filters, engine components such as pistons and gaskets, and thermal management parts."),
    dict(slug="mann", name="MANN-FILTER", group="MANN+HUMMEL", hq="Germany", tier="OE Manufacturer",
         systems=["filtration", "commercial"], catalog="https://www.mann-filter.com/",
         desc="OE-quality oil, air, fuel and cabin filters for cars, trucks and off-highway machines."),
    dict(slug="provia", name="ProVia", group="ZF Group (WABCO)", hq="Germany", tier="Value Line",
         systems=["commercial", "braking"], catalog="https://provia-auto.com/wp-content/plugins/brandapi/assets/ProVia_Product-Catalogue_en.pdf",
         desc="Cost-effective commercial-vehicle parts line, including air-brake and braking components."),
    dict(slug="purflux", name="PURFLUX", group="Sogefi", hq="Italy", tier="OE Manufacturer",
         systems=["filtration"], catalog="https://www.purflux.com/en/index.html",
         desc="Oil, air, fuel and cabin filters, widely fitted as original equipment by French car makers."),
    dict(slug="sachs", name="SACHS", group="ZF Group", hq="Germany", tier="OE Manufacturer",
         systems=["transmission", "suspension"], catalog=ZF,
         desc="Clutch systems, dual-mass flywheels, shock absorbers and suspension components."),
    dict(slug="zf-parts", name="ZF Parts", group="ZF Group", hq="Germany", tier="OE Manufacturer",
         systems=["transmission", "suspension", "commercial"], catalog=ZF,
         desc="Transmission service kits, driveline and chassis parts from one of the world's largest OE suppliers."),
    dict(slug="swag", name="SWAG", group="bilstein group", hq="Germany", tier="Premium Aftermarket",
         systems=["suspension", "engine", "cooling", "braking"], catalog=BILSTEIN,
         desc="Practical, reliable replacement parts with strong coverage for European vehicles."),
    dict(slug="textar", name="TEXTAR", group="TMD Friction", hq="Germany", tier="OE Manufacturer",
         systems=["braking", "commercial"], catalog="https://textar.com/en/brakebook/",
         desc="Brake pads, discs and drums for cars and commercial vehicles, developed with OE vehicle makers."),
    dict(slug="trw", name="TRW", group="ZF Group", hq="Germany", tier="OE Manufacturer",
         systems=["braking", "suspension"], catalog=ZF,
         desc="Braking, steering and suspension parts, from pads and discs to steering racks and joints."),
    dict(slug="valeo", name="Valeo", group="Valeo", hq="France", tier="OE Manufacturer",
         systems=["transmission", "electrical", "cooling"], catalog="https://www.valeoservice.com/en-com/catalogs",
         desc="Clutch kits, wipers, lighting, starters and alternators, and thermal and climate components."),
    dict(slug="vdo", name="VDO", group="AUMOVIO (formerly Continental)", hq="Germany", tier="OE Manufacturer",
         systems=["electrical", "fuel"], catalog=CONTI,
         desc="Fuel pumps, sensors, actuators and vehicle electronics for passenger and commercial vehicles."),
    dict(slug="wabco", name="WABCO", group="ZF Group", hq="Germany", tier="OE Manufacturer",
         systems=["commercial", "braking"], catalog=ZF,
         desc="Air-brake, braking-control and air-management systems for trucks, buses and trailers."),
    dict(slug="vitesco", name="Vitesco Technologies", group="Schaeffler", hq="Germany", tier="OE Manufacturer",
         systems=["fuel", "electrical"], catalog=SCHAEFFLER,
         desc="Fuel injectors, pumps, sensors and powertrain electronics manufactured to OE standards."),
]
